const actions = {
    IS_LOADING: "IS_LOADING",
    DELETE_IS_LOADING: "DELETE_IS_LOADING",
    SUBMIT_IS_LOADING: "SUBMIT_IS_LOADING",

    LOAD_DATA_SUCCESS: "LOAD_DATA_SUCCESS",
    LOAD_DATA_FAILURE: "LOAD_DATA_FAILURE",
    POST_DATA_SUCCESS: "POST_DATA_SUCCESS",
    POST_DATA_FAILURE: "POST_DATA_FAILURE",
    EDIT_DATA_SUCCESS: "EDIT_DATA_SUCCESS",
    EDIT_DATA_FAILURE: "EDIT_DATA_FAILURE",
    DELETE_DATA_SUCCESS: "DELETE_DATA_SUCCESS",
    DELETE_DATA_FAILURE: "DELETE_DATA_FAILURE",

    // DELETE_POST_LIST: "DELETE_POST_LIST",
    // DELETE_POST_LIST_SUCCESS: "DELETE_POST_LIST_SUCCESS",
    // DELETE_POST_LIST_FAILURE: "DELETE_POST_LIST_FAILURE",

    // LOAD_A_POST_SUCCESS: "LOAD_A_POST_SUCCESS",
    // LOAD_A_POST_FAILURE: "LOAD_A_POST_FAILURE",

    // SUBMIT_POST_SUCCESS: "SUBMIT_POST_SUCCESS",
    // SUBMIT_POST_FAILURE: "SUBMIT_POST_FAILURE",

    // UPDATE_POST: "UPDATE_POST",
    // UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
    // UPDATE_POST_FAILURE: "UPDATE_POST_FAILURE",
};

export default actions;