const actions = {

    LOAD_DATA_SUCCESS: "LOAD_DATA_SUCCESS",
    LOAD_DATA_FAILURE: "LOAD_DATA_FAILURE",
    POST_DATA_SUCCESS: "POST_DATA_SUCCESS",
    POST_DATA_FAILURE: "POST_DATA_FAILURE",
    EDIT_DATA_SUCCESS: "EDIT_DATA_SUCCESS",
    EDIT_DATA_FAILURE: "EDIT_DATA_FAILURE",
    DELETE_DATA_SUCCESS: "DELETE_DATA_SUCCESS",
    DELETE_DATA_FAILURE: "DELETE_DATA_FAILURE",

};

export default actions;